#pragma once
#include "SpecSyncTypes.h"
#include <functional>
#include <unordered_map>
#include <vector>

namespace SpecSync {

    // A callback function type that takes the new float value
    using SettingCallback = std::function<void(float)>;

    class SettingsRegistry {
    public:
        // Let the game engine register how to change a specific setting
        void BindSetting(Setting target, SettingCallback callback);

        // SpecSync calls this to execute the commands generated by the OptimizationEngine
        void ExecuteCommands(const std::vector<OptimizationCommand>& commands);

    private:
        std::unordered_map<Setting, SettingCallback> m_Callbacks;
    };

}